version: '3.8'
services:
  jupyter-notebook:
    image: jupyter/scipy-notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - "10000:8888"
    networks:
      - opensearch

  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Naotoiso19911104%
      - "plugins.ml_commons.rag_pipeline_feature_enabled=true"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch

networks:
  opensearch:
    driver: bridge
